<?php

/**
 * @file
 * Install functions for LocalGov Services.
 */

/**
 * Update localgov_services_menu machine name to use hypens.
 */
function localgov_services_update_10001(): void {

  // Check if an existing new menu exists, assume it was renamed already.
  $existing = \Drupal::entityTypeManager()->getStorage('menu')->load('localgov-services-menu');
  if ($existing) {
    return;
  }

  // Create the new hyphen seperated localgov-services-menu.
  \Drupal::entityTypeManager()->getStorage('menu')
    ->create([
      'langcode' => 'en',
      'status' => TRUE,
      'id' => 'localgov-services-menu',
      'label' => 'Services menu',
      'description' => 'Service links',
      'locked' => FALSE,
    ])->save();

  // Load existing menu link content items.
  $items = \Drupal::entityTypeManager()->getStorage('menu_link_content')->loadByProperties([
    'menu_name' => 'localgov_services_menu',
  ]);

  // Update current menu link content items to point to the new menu.
  foreach ($items as $item) {
    $new_item = $item->createDuplicate();
    $new_item->set('menu_name', 'localgov-services-menu')->save();
  }

  // Label as the old underscores seperated localgov_services_menu.
  \Drupal::entityTypeManager()
    ->getStorage('menu')
    ->load('localgov_services_menu')
    ->set('label', 'Services menu (Old)')
    ->set('description', 'Old Service links with broken machine name. Delete this menu once you replace your services menu blocks.')
    ->save();

}
