<?php

/**
 * Implements hook_theme().
 */
function bhcc_service_hub_theme($existing, $type, $theme, $path) {
  return [
    'service_updates' => [
      'variables' => [
        'items' => array()
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bhcc_service_hub_preprocess_node(&$variables) {
  /** @var \Drupal\bhcc_service_hub\Node\ServiceHUB $node */
  $node = $variables['node'];

  if ($node->bundle() == 'service_hub') {

    if ($variables['view_mode'] == 'full') {
      $variables['field_facebook'] = $node->hasFacebook() ? $node->getFacebook()['value'] : '';
      $variables['field_twitter'] = $node->hasTwitter() ? $node->getTwitter()['value'] : '';
      $variables['field_phone'] = $node->hasPhoneNumber() ? $node->getPhoneNumber()['value'] : '';
      $variables['field_hearing_difficulties_phone'] = $node->hasHearingDifficultiesPhone() ? $node->getHearingDifficultiesPhone()['value'] : '';
      $variables['field_email_address'] = $node->hasEmailAddress() ? $node->getEmailAddress()['value'] : '';
      $variables['field_address_first_line'] = $node->hasAddressFirstLine() ? $node->getAddressFirstLine()['value'] : '';
      $variables['field_link_to_map'] = $node->hasLinkToMap() ? $node->getLinkToMap()['uri'] : '';

      if ($node->showServiceUpdates()) {
        $variables['service_updates'] = [
          '#theme' => 'service_updates',
          '#items' => Drupal::service('bhcc_service_hub.service_updates')->getUpdatesForBlock($node)
        ];
      }
    }
  }
}
