<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_presave().
 */
function localgov_services_page_entity_presave(EntityInterface $entity) {
  if ($entity instanceof NodeInterface && $entity->bundle() == 'localgov_services_page') {
    // Migrate all topic fields into field_all_topics so we can index on it
    // later.
    $topics = array_merge($entity->get('field_topic_term')->getValue(), $entity->get('field_private_topics')->getValue());
    $entity->get('field_all_topics')->setValue($topics);
  }
}
