<?php

/**
 * @file
 * Local Government Services section navigation.
 *
 *   Some of the functionality is related to field that a reused outside the
 *   Services node bundles. Within the services section navigation integrates
 *   the bundles, so this is an attempt to collect this functionality together,
 *   and in the future make refactoring it easier.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\pathauto\Entity\PathautoPattern;

/**
 * Implements hook_field_wiget_WIDGET_ID_alter().
 */
function localgov_services_navigation_field_widget_entity_reference_autocomplete_form_alter(&$element, FormStateInterface $form_state, $context) {
  if (!empty($element['target_id']) && $element['target_id']['#selection_handler'] == 'localgov_services') {
    $element['target_id']['#value_callback'] = ['Drupal\localgov_services_navigation\EntityReferenceValue', 'valueCallback'];
  }
}

/**
 * Implements hook_pathauto_pattern_alter().
 */
function localgov_services_navigation_pathauto_pattern_alter(PathautoPattern $pattern, array $context) {
  // If pathauto isn't set to include this entity into services hierarchy, but
  // it has opt-ed in with the field add the (optional) parent to the path.
  $entity = reset($context['data']);
  assert($entity instanceof ContentEntityInterface);
  if ($entity->hasField('localgov_services_parent') && strpos($pattern->getPattern(), '[node:localgov_services_parent:entity:url:relative]') === FALSE) {
    $pattern->setPattern('[node:localgov_services_parent:entity:url:relative]/' . $pattern->getPattern());
  }
}
