<?php

/**
 * @file
 * LocalGovDrupal service status page module file.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function localgov_services_status_theme($existing, $type, $theme, $path) {
  return [
    'service_updates_block' => [
      'variables' => [
        'items' => [],
        'see_all_link' => NULL,
      ],
    ],
    'service_updates_page' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'service_status' => [
      'render element' => 'block',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function localgov_services_status_node_presave(EntityInterface $entity) {
  // Invalidate cache for landing page when saving status page.
  if ($entity->bundle() === 'localgov_services_status') {
    if (!$entity->get('field_service')->isEmpty()) {
      $invalidate_node_id = $entity->get('field_service')->first()->getValue()['target_id'];
      Cache::invalidateTags(['node:' . $invalidate_node_id]);
    }
  }
}
