<?php

/**
 * Implements hook_theme().
 */
function localgov_services_landing_theme($existing, $type, $theme, $path) {
  return [
    'service_updates_block' => [
      'variables' => [
        'items' => array(),
        'see_all_link' => null
      ],
    ],
    'service_updates_page' => [
      'variables' => [
        'items' => array()
      ],
    ],
    'service_status' => [
      'render element' => 'block'
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function localgov_services_landing_preprocess_node(&$variables) {
  /** @var \Drupal\Entity\NodeInterface $node */
  $node = $variables['node'];

  if ($node->bundle() == 'localgov_services_landing') {

    //
    // @TODO this is dumping the raw values from the node fields into the
    // variables available to twig.
    //  - WHY? Can they not just be accessed "normally"?
    //  - RENDERED? Are we sanitizing and rendering.
    //
    if ($variables['view_mode'] == 'full') {
      $variables['field_facebook'] = $node->get('field_facebook')->isEmpty() ? '' : $node->get('field_facebook')->first()->getValue()['value'];
      $variables['field_twitter'] = $node->get('field_twitter')->isEmpty() ? '' : $node->get('field_twitter')->first()->getValue()['value'];
      $variables['field_phone'] = $node->get('field_phone')->isEmpty() ? '' : $node->get('field_phone')->first()->getValue()['value'];
      $variables['field_contact_us_online'] = $node->get('field_contact_us_online')->isEmpty() ? '' : $node->get('field_contact_us_online')->first()->getValue()['value'];
      $variables['field_other_team_contacts'] = $node->get('field_other_team_contacts')->isEmpty() ? '' : $node->get('field_other_team_contacts')->first()->getValue()['value'];
      $variables['field_hearing_difficulties_phone'] = $node->get('field_hearing_difficulties_phone')->isEmpty() ? '' : $node->get('field_hearing_difficulties_phone')->first()->getValue()['value'];
      $variables['field_email_address'] = $node->get('field_email_address')->isEmpty() ? '' : $node->get('field_email_address')->first()->getValue()['value'];
      $variables['field_address_first_line'] = $node->get('field_address_first_line')->isEmpty() ? $node->get('field_address_first_line')->first()->getValue()['value'] : '';
      $variables['field_link_to_map'] = $node->get('field_link_to_map')->isEmpty() ? '' : $node->get('field_link_to_map')->first()->getValue()['uri'];

      if ($node->get('field_enable_service_updates')->first()->getValue()) {
        $variables['service_updates'] = [
          '#theme' => 'service_updates_block',
          '#items' => Drupal::service('localgov_services_status.service_updates')->getUpdatesForBlock($node),
          '#see_all_link' => \Drupal\Core\Url::fromRoute('service_update_' . $node->id())
        ];
      }
    }
  }
}
