<?php

/**
 * @file
 * LocalGov services subanding install file.
 */

use Drupal\localgov_core\FieldRenameHelper;

/**
 * Update Field names in localgov services sublanding.
 *
 * Field mapping between existing and new names:
 * field_topics => localgov_topics.
 */
function localgov_services_sublanding_update_8001(&$sandbox) {

  // Update field_ types fields provided by localgov_services_sublanding.
  FieldRenameHelper::renameField('field_topics', 'localgov_topics', 'node');
}
